// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrismaRH.Infraestrutura.Persistencia;

#nullable disable

namespace PrismaRH.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(PrismaRhDbContext))]
    [Migration("20260828124623_TipoDeFolha")]
    partial class TipoDeFolha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IdOrganizacao", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_cargos_organizacao_codigo");

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.ContratoTrabalho", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataAdmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_admissao");

                    b.Property<DateOnly?>("DataDesligamento")
                        .HasColumnType("date")
                        .HasColumnName("data_desligamento");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa");

                    b.Property<Guid>("IdFuncionario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_funcionario");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("matricula");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.HasIndex("IdFuncionario")
                        .HasDatabaseName("ix_contratos_funcionario");

                    b.HasIndex("IdEmpresa", "Matricula")
                        .IsUnique()
                        .HasDatabaseName("ix_contratos_empresa_matricula");

                    b.ToTable("contratos_trabalho", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.VigenciaContrato", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdCargo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cargo");

                    b.Property<Guid>("IdContrato")
                        .HasColumnType("uuid")
                        .HasColumnName("id_contrato");

                    b.Property<Guid>("IdEstabelecimento")
                        .HasColumnType("uuid")
                        .HasColumnName("id_estabelecimento");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<int>("JornadaMensalHoras")
                        .HasColumnType("integer")
                        .HasColumnName("jornada_mensal_horas");

                    b.Property<int>("Motivo")
                        .HasColumnType("integer")
                        .HasColumnName("motivo");

                    b.Property<decimal>("Salario")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("salario");

                    b.Property<DateOnly?>("ValidoAte")
                        .HasColumnType("date")
                        .HasColumnName("valido_ate");

                    b.Property<DateOnly>("ValidoDe")
                        .HasColumnType("date")
                        .HasColumnName("valido_de");

                    b.HasKey("Id");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdEstabelecimento");

                    b.HasIndex("IdContrato", "ValidoDe")
                        .HasDatabaseName("ix_vigencias_contrato_inicio");

                    b.ToTable("vigencias_contrato", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("razao_social");

                    b.HasKey("Id");

                    b.HasIndex("IdOrganizacao", "Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_organizacao_cnpj");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Empresas.Estabelecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_estabelecimentos_empresa_codigo");

                    b.ToTable("estabelecimentos", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Ferias.ConcessaoFerias", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<int>("Dias")
                        .HasColumnType("integer")
                        .HasColumnName("dias");

                    b.Property<int>("DiasAbonoPecuniario")
                        .HasColumnType("integer")
                        .HasColumnName("dias_abono_pecuniario");

                    b.Property<DateOnly>("FimPeriodoAquisitivo")
                        .HasColumnType("date")
                        .HasColumnName("fim_periodo_aquisitivo");

                    b.Property<Guid>("IdContrato")
                        .HasColumnType("uuid")
                        .HasColumnName("id_contrato");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("date")
                        .HasColumnName("inicio");

                    b.Property<DateOnly>("InicioPeriodoAquisitivo")
                        .HasColumnType("date")
                        .HasColumnName("inicio_periodo_aquisitivo");

                    b.HasKey("Id");

                    b.HasIndex("IdContrato");

                    b.HasIndex("IdOrganizacao", "IdContrato")
                        .HasDatabaseName("ix_concessoes_ferias_organizacao_contrato");

                    b.ToTable("concessoes_ferias", null, t =>
                        {
                            t.HasCheckConstraint("ck_concessoes_ferias_dias", "dias >= 0\nAND dias_abono_pecuniario >= 0\nAND (dias + dias_abono_pecuniario) > 0\nAND inicio > fim_periodo_aquisitivo\nAND fim_periodo_aquisitivo > inicio_periodo_aquisitivo");
                        });
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.BaseApurada", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Base")
                        .HasColumnType("integer")
                        .HasColumnName("base");

                    b.Property<Guid>("IdFolhaFuncionario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_folha_funcionario");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdFolhaFuncionario", "Base")
                        .IsUnique()
                        .HasDatabaseName("ux_bases_apuradas_holerite_base");

                    b.ToTable("bases_apuradas", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.FolhaFuncionario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Avos")
                        .HasColumnType("integer")
                        .HasColumnName("avos");

                    b.Property<int>("Divisor")
                        .HasColumnType("integer")
                        .HasColumnName("divisor");

                    b.Property<Guid>("IdContrato")
                        .HasColumnType("uuid")
                        .HasColumnName("id_contrato");

                    b.Property<Guid>("IdFolha")
                        .HasColumnType("uuid")
                        .HasColumnName("id_folha");

                    b.Property<Guid>("IdFuncionario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_funcionario");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<Guid?>("IdVigenciaReferencia")
                        .HasColumnType("uuid")
                        .HasColumnName("id_vigencia_referencia");

                    b.Property<decimal>("Liquido")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("liquido");

                    b.Property<int>("QuantidadeDependentesIrrf")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalarioReferencia")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("salario_referencia");

                    b.Property<decimal>("TotalDescontos")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_descontos");

                    b.Property<decimal>("TotalProventos")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_proventos");

                    b.HasKey("Id");

                    b.HasIndex("IdContrato");

                    b.HasIndex("IdFuncionario");

                    b.HasIndex("IdVigenciaReferencia");

                    b.HasIndex("IdFolha", "IdContrato")
                        .IsUnique()
                        .HasDatabaseName("ux_folhas_funcionario_folha_contrato");

                    b.ToTable("folhas_funcionario", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.FolhaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CalculadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculada_em");

                    b.Property<int>("Competencia")
                        .HasColumnType("integer")
                        .HasColumnName("competencia");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset?>("FechadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechada_em");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<int>("Tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("tipo");

                    b.Property<decimal>("TotalDescontos")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_descontos");

                    b.Property<decimal>("TotalLiquido")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_liquido");

                    b.Property<decimal>("TotalProventos")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_proventos");

                    b.Property<int>("VersaoCalculo")
                        .HasColumnType("integer")
                        .HasColumnName("versao_calculo");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa", "Competencia", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ux_folhas_empresa_competencia_tipo");

                    b.ToTable("folhas_pagamento", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.LancamentoFolha", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BasesIncidentes")
                        .HasColumnType("integer")
                        .HasColumnName("bases_incidentes");

                    b.Property<string>("CodigoRubrica")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_rubrica");

                    b.Property<int>("Estrategia")
                        .HasColumnType("integer")
                        .HasColumnName("estrategia");

                    b.Property<Guid>("IdFolhaFuncionario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_folha_funcionario");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<Guid>("IdRubrica")
                        .HasColumnType("uuid")
                        .HasColumnName("id_rubrica");

                    b.Property<string>("NomeRubrica")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome_rubrica");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("Origem")
                        .HasColumnType("integer")
                        .HasColumnName("origem");

                    b.Property<string>("Referencia")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("referencia");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdRubrica");

                    b.HasIndex("IdFolhaFuncionario", "Ordem")
                        .HasDatabaseName("ix_lancamentos_folha_ordem");

                    b.ToTable("lancamentos_folha", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.LinhaMemoriaCalculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Expressao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("expressao");

                    b.Property<Guid>("IdLancamento")
                        .HasColumnType("uuid")
                        .HasColumnName("id_lancamento");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdLancamento", "Ordem")
                        .HasDatabaseName("ix_memorias_calculo_ordem");

                    b.ToTable("memorias_calculo", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.Rubrica", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<int>("BasesIncidentes")
                        .HasColumnType("integer")
                        .HasColumnName("bases_incidentes");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("Estrategia")
                        .HasColumnType("integer")
                        .HasColumnName("estrategia");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("IdOrganizacao")
                        .IsUnique()
                        .HasDatabaseName("ux_rubricas_fgts_ativa")
                        .HasFilter("estrategia = 4 AND ativa");

                    b.HasIndex("IdOrganizacao", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_rubricas_organizacao_codigo");

                    b.ToTable("rubricas", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Identidade.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("organizacoes", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Identidade.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<Guid?>("SubstituidoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("substituido_por_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_refresh_tokens_usuario");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("IdOrganizacao")
                        .HasDatabaseName("ix_usuarios_organizacao");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Parametros.FaixaInss", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Aliquota")
                        .HasPrecision(7, 6)
                        .HasColumnType("numeric(7,6)")
                        .HasColumnName("aliquota");

                    b.Property<Guid>("IdTabelaInss")
                        .HasColumnType("uuid")
                        .HasColumnName("id_tabela_inss");

                    b.Property<decimal>("LimiteSuperior")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("limite_superior");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.HasKey("Id");

                    b.HasIndex("IdTabelaInss", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("ux_faixas_inss_tabela_ordem");

                    b.ToTable("faixas_inss", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Parametros.FaixaIrrf", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Aliquota")
                        .HasPrecision(7, 6)
                        .HasColumnType("numeric(7,6)")
                        .HasColumnName("aliquota");

                    b.Property<Guid>("IdTabelaIrrf")
                        .HasColumnType("uuid")
                        .HasColumnName("id_tabela_irrf");

                    b.Property<decimal?>("LimiteSuperior")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("limite_superior");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<decimal>("ParcelaADeduzir")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("parcela_a_deduzir");

                    b.HasKey("Id");

                    b.HasIndex("IdTabelaIrrf", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("ux_faixas_irrf_tabela_ordem");

                    b.ToTable("faixas_irrf", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Parametros.TabelaFgts", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Aliquota")
                        .HasPrecision(7, 6)
                        .HasColumnType("numeric(7,6)")
                        .HasColumnName("aliquota");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("fonte");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_inicio");

                    b.HasKey("Id");

                    b.HasIndex("VigenciaInicio")
                        .IsUnique()
                        .HasDatabaseName("ux_tabelas_fgts_vigencia_inicio");

                    b.ToTable("tabelas_fgts", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Parametros.TabelaInss", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("fonte");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_inicio");

                    b.HasKey("Id");

                    b.HasIndex("VigenciaInicio")
                        .IsUnique()
                        .HasDatabaseName("ux_tabelas_inss_vigencia_inicio");

                    b.ToTable("tabelas_inss", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Parametros.TabelaIrrf", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal>("DeducaoPorDependente")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("deducao_por_dependente");

                    b.Property<decimal>("DescontoSimplificado")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("desconto_simplificado");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("fonte");

                    b.Property<decimal>("RedutorBase")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("redutor_base");

                    b.Property<decimal>("RedutorCoeficiente")
                        .HasPrecision(7, 6)
                        .HasColumnType("numeric(7,6)")
                        .HasColumnName("redutor_coeficiente");

                    b.Property<DateOnly>("VigenciaInicio")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_inicio");

                    b.HasKey("Id");

                    b.HasIndex("VigenciaInicio")
                        .IsUnique()
                        .HasDatabaseName("ux_tabelas_irrf_vigencia_inicio");

                    b.ToTable("tabelas_irrf", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Pessoas.Dependente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<DateOnly?>("FimDeducaoIrrf")
                        .HasColumnType("date")
                        .HasColumnName("fim_deducao_irrf");

                    b.Property<Guid>("IdFuncionario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_funcionario");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<DateOnly?>("InicioDeducaoIrrf")
                        .HasColumnType("date")
                        .HasColumnName("inicio_deducao_irrf");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Relacao")
                        .HasColumnType("integer")
                        .HasColumnName("relacao");

                    b.HasKey("Id");

                    b.HasIndex("IdFuncionario");

                    b.HasIndex("IdOrganizacao", "IdFuncionario")
                        .HasDatabaseName("ix_dependentes_organizacao_funcionario");

                    b.ToTable("dependentes", null, t =>
                        {
                            t.HasCheckConstraint("ck_dependentes_periodo_deducao", "(inicio_deducao_irrf IS NOT NULL OR fim_deducao_irrf IS NULL)\nAND (fim_deducao_irrf IS NULL OR fim_deducao_irrf >= inicio_deducao_irrf)");
                        });
                });

            modelBuilder.Entity("PrismaRH.Dominio.Pessoas.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_funcionarios_nome");

                    b.HasIndex("IdOrganizacao", "Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_funcionarios_organizacao_cpf");

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.Cargo", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.ContratoTrabalho", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaRH.Dominio.Pessoas.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.VigenciaContrato", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Contratos.Cargo", null)
                        .WithMany()
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaRH.Dominio.Contratos.ContratoTrabalho", null)
                        .WithMany("Vigencias")
                        .HasForeignKey("IdContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaRH.Dominio.Empresas.Estabelecimento", null)
                        .WithMany()
                        .HasForeignKey("IdEstabelecimento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Empresas.Empresa", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Empresas.Estabelecimento", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Ferias.ConcessaoFerias", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Contratos.ContratoTrabalho", null)
                        .WithMany()
                        .HasForeignKey("IdContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.BaseApurada", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Folha.FolhaFuncionario", null)
                        .WithMany("Bases")
                        .HasForeignKey("IdFolhaFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.FolhaFuncionario", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Contratos.ContratoTrabalho", null)
                        .WithMany()
                        .HasForeignKey("IdContrato")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaRH.Dominio.Folha.FolhaPagamento", null)
                        .WithMany("Funcionarios")
                        .HasForeignKey("IdFolha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaRH.Dominio.Pessoas.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaRH.Dominio.Contratos.VigenciaContrato", null)
                        .WithMany()
                        .HasForeignKey("IdVigenciaReferencia")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.FolhaPagamento", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.LancamentoFolha", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Folha.FolhaFuncionario", null)
                        .WithMany("Lancamentos")
                        .HasForeignKey("IdFolhaFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaRH.Dominio.Folha.Rubrica", null)
                        .WithMany()
                        .HasForeignKey("IdRubrica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.LinhaMemoriaCalculo", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Folha.LancamentoFolha", null)
                        .WithMany("Memoria")
                        .HasForeignKey("IdLancamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Identidade.RefreshToken", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Identidade.Usuario", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Parametros.FaixaInss", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Parametros.TabelaInss", null)
                        .WithMany("Faixas")
                        .HasForeignKey("IdTabelaInss")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Parametros.FaixaIrrf", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Parametros.TabelaIrrf", null)
                        .WithMany("Faixas")
                        .HasForeignKey("IdTabelaIrrf")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Pessoas.Dependente", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Pessoas.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Pessoas.Funcionario", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.ContratoTrabalho", b =>
                {
                    b.Navigation("Vigencias");
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.FolhaFuncionario", b =>
                {
                    b.Navigation("Bases");

                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.FolhaPagamento", b =>
                {
                    b.Navigation("Funcionarios");
                });

            modelBuilder.Entity("PrismaRH.Dominio.Folha.LancamentoFolha", b =>
                {
                    b.Navigation("Memoria");
                });

            modelBuilder.Entity("PrismaRH.Dominio.Parametros.TabelaInss", b =>
                {
                    b.Navigation("Faixas");
                });

            modelBuilder.Entity("PrismaRH.Dominio.Parametros.TabelaIrrf", b =>
                {
                    b.Navigation("Faixas");
                });
#pragma warning restore 612, 618
        }
    }
}
