// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrismaRH.Infraestrutura.Persistencia;

#nullable disable

namespace PrismaRH.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(PrismaRhDbContext))]
    [Migration("20260823031237_CadastroFuncionalDeRh")]
    partial class CadastroFuncionalDeRh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IdOrganizacao", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_cargos_organizacao_codigo");

                    b.ToTable("cargos", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.ContratoTrabalho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataAdmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_admissao");

                    b.Property<DateOnly?>("DataDesligamento")
                        .HasColumnType("date")
                        .HasColumnName("data_desligamento");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa");

                    b.Property<Guid>("IdFuncionario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_funcionario");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("matricula");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.HasIndex("IdFuncionario")
                        .HasDatabaseName("ix_contratos_funcionario");

                    b.HasIndex("IdEmpresa", "Matricula")
                        .IsUnique()
                        .HasDatabaseName("ix_contratos_empresa_matricula");

                    b.ToTable("contratos_trabalho", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.VigenciaContrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdCargo")
                        .HasColumnType("uuid")
                        .HasColumnName("id_cargo");

                    b.Property<Guid>("IdContrato")
                        .HasColumnType("uuid")
                        .HasColumnName("id_contrato");

                    b.Property<Guid>("IdEstabelecimento")
                        .HasColumnType("uuid")
                        .HasColumnName("id_estabelecimento");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<int>("JornadaMensalHoras")
                        .HasColumnType("integer")
                        .HasColumnName("jornada_mensal_horas");

                    b.Property<int>("Motivo")
                        .HasColumnType("integer")
                        .HasColumnName("motivo");

                    b.Property<decimal>("Salario")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("salario");

                    b.Property<DateOnly?>("ValidoAte")
                        .HasColumnType("date")
                        .HasColumnName("valido_ate");

                    b.Property<DateOnly>("ValidoDe")
                        .HasColumnType("date")
                        .HasColumnName("valido_de");

                    b.HasKey("Id");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdContrato")
                        .IsUnique()
                        .HasDatabaseName("ix_vigencias_uma_aberta_por_contrato")
                        .HasFilter("valido_ate IS NULL");

                    b.HasIndex("IdEstabelecimento");

                    b.HasIndex("IdContrato", "ValidoDe")
                        .HasDatabaseName("ix_vigencias_contrato_inicio");

                    b.ToTable("vigencias_contrato", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("razao_social");

                    b.HasKey("Id");

                    b.HasIndex("IdOrganizacao", "Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_organizacao_cnpj");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Empresas.Estabelecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid")
                        .HasColumnName("id_empresa");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_estabelecimentos_empresa_codigo");

                    b.ToTable("estabelecimentos", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Identidade.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("organizacoes", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Identidade.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("id_usuario");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<Guid?>("SubstituidoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("substituido_por_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_refresh_tokens_usuario");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Perfil")
                        .HasColumnType("integer")
                        .HasColumnName("perfil");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("IdOrganizacao")
                        .HasDatabaseName("ix_usuarios_organizacao");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Pessoas.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<Guid>("IdOrganizacao")
                        .HasColumnType("uuid")
                        .HasColumnName("id_organizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_funcionarios_nome");

                    b.HasIndex("IdOrganizacao", "Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_funcionarios_organizacao_cpf");

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.Cargo", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.ContratoTrabalho", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaRH.Dominio.Pessoas.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.VigenciaContrato", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Contratos.Cargo", null)
                        .WithMany()
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaRH.Dominio.Contratos.ContratoTrabalho", null)
                        .WithMany("Vigencias")
                        .HasForeignKey("IdContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaRH.Dominio.Empresas.Estabelecimento", null)
                        .WithMany()
                        .HasForeignKey("IdEstabelecimento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Empresas.Empresa", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Empresas.Estabelecimento", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Identidade.RefreshToken", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Identidade.Usuario", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Pessoas.Funcionario", b =>
                {
                    b.HasOne("PrismaRH.Dominio.Identidade.Organizacao", null)
                        .WithMany()
                        .HasForeignKey("IdOrganizacao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PrismaRH.Dominio.Contratos.ContratoTrabalho", b =>
                {
                    b.Navigation("Vigencias");
                });
#pragma warning restore 612, 618
        }
    }
}
